server:
  port: 8099

spring:
  application:
    name: electronicwaybill
  datasource:
    url: jdbc:mysql://47.105.48.236:3306/sql_yiguan?autoReconnect=true&characterEncoding=utf-8
    username: sql_yiguan
    password: peBdLWke5zSSYmHZ
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.huagongwuliu.waybillelectronic.pojo
  configuration:
    #开启自动下划线格式转驼峰格式
    map-underscore-to-camel-case: true
    #mybatis-plus:
    #  typeAliasesPackage: com.huagongwuliu.waybillelectronic.pojo


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.huagongwuliu.waybillelectronic.mapper: debug



