server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///eesy
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html
mybatis:
  type-aliases-package: com.huagongwuliu.waybillelectronic.pojo
  configuration:
    #开启自动下划线格式转驼峰格式
    map-underscore-to-camel-case: true
#mybatis-plus:
#  typeAliasesPackage: com.huagongwuliu.waybillelectronic.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.huagongwuliu.waybillelectronic.mapper : debug

